Need to get my head back into this plugin

diff --git a/bin/vit b/bin/vit
--- a/bin/vit
+++ b/bin/vit
@@ -1,19 +1,24 @@
-#!/bin/bash
+#!/bin/sh
 
 [ "$1" == "-h" -o "$1" == "--help" ] && {
-    echo "USAGE: `basename $0` [file]" >&2
+    echo "USAGE: `basename $0` [file]"
     exit
 }
 
-git rev-parse --is-inside-work-tree >/dev/null 2>&1 || {
-    [ $# -gt 0 ] && $(cd $(dirname $1) && git rev-parse --is-inside-work-tree >/dev/null 2>&1) || {
-        echo "Could not find a git working tree" >&2
-        exit 1
-    }
+[ $# -gt 0 ] && {
+    origdir=$PWD
+    cd `dirname $1`
 }
 
+git rev-parse --is-inside-work-tree >/dev/null 2>&1 || {
+    echo "Could not find a git working tree" >&2
+    exit 1
+}
+
+[ -z ${origdir+x} ] && cd ${origdir}
+
 exec vim --cmd "let g:vit_standalone=1" \
-         -c "Git log "$1 \
+         -c "Git log" \
          -c "Git status" \
          -c "wincmd t" \
          $@
