Much smarter at bailing out when confused, per #45

diff --git a/bin/vit b/bin/vit
--- a/bin/vit
+++ b/bin/vit
@@ -5,9 +5,11 @@
     exit
 }
 
-git rev-pasre --is-inside-work-tree >/dev/null 2>&1 || {
-    echo "Not inside a git working tree" >&2
-    exit 1
+git rev-parse --is-inside-work-tree >/dev/null 2>&1 || {
+    [ $# -gt 0 ] && $(cd $(dirname $1) && git rev-parse --is-inside-work-tree >/dev/null 2>&1) || {
+        echo "Could not find a git working tree" >&2
+        exit 1
+    }
 }
 
 exec vim -c "Git log "$1 \
